# Generated by Django 5.2.14 on 2026-05-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('EmployeeId', models.CharField(blank=True, max_length=50, unique=True)),
                ('ProjectInvolved', models.CharField(max_length=100)),
                ('IsAdmin', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('LoginTime', models.DateTimeField(auto_now_add=True)),
                ('LogoutTime', models.DateTimeField(blank=True, null=True)),
                ('WorkStatus', models.CharField(max_length=20)),
                ('EmployeeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
