# Generated by Django 5.2.14 on 2026-05-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('EmployeeId', models.CharField(max_length=50, unique=True)),
                ('ProjectInvolved', models.CharField(max_length=100)),
                ('IsAdmin', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('LoginTime', models.DateTimeField(auto_now_add=True)),
                ('LogoutTime', models.DateTimeField(blank=True, null=True)),
                ('WorkStatus', models.CharField(max_length=20)),
                ('EmployeeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
