# Generated by Django 5.2.14 on 2026-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='FirstName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='LastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
