# Generated by Django 5.2.14 on 2026-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_firstname_employee_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
    ]
