# Generated by Django 5.2.14 on 2026-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='EmployeeRef',
            new_name='employee_ref',
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='LogId',
            new_name='log_id',
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='LoginTime',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='LogoutTime',
            new_name='logout_time',
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='WorkStatus',
            new_name='work_status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeId',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='IsActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='IsAdmin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ProjectInvolved',
            new_name='project_involved',
        ),
    ]
